# Feature engineering

## Imports

In [1]:
import os
import pickle
import time
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

## Functions

In [2]:
def find_30day_extreme(in_df, in_column, in_agg):
    """
    Calculates a rolling window mean. Then determines the min/max/mean 
    value of all the window aggregates.
    Window size: 30 days.
    in_df: input dataframe
    in_column: column to be aggregated
    in_agg: aggregation function for the list of results ('min','max','mean')
    """
    # Pandas 30 day rolling window. Make sure there are at least 10 samples in the window.
    agg_df = in_df[[in_column,'Date']].rolling('30d', on='Date', min_periods=10).mean()
    agg_list = agg_df[in_column]
    if in_agg == 'min':
        return np.min(agg_list)
    if in_agg == 'max':
        return np.max(agg_list)
    if in_agg == 'mean':
        return np.mean(agg_list)

In [3]:
def calculate_features(tmp_df):
    result = []
    # Minimum average temperature in 30-day period
    result.append(find_30day_extreme(tmp_df, 'temperatureAverage', in_agg='min'))
    # Maximum average temperature in 30-day period
    result.append(find_30day_extreme(tmp_df, 'temperatureAverage', in_agg='max'))
    # Mean temperature difference and variance
    result.append(tmp_df['NDVI'].mean())
    result.append(tmp_df['dewPoint'].mean())
    result.append(tmp_df['cloudCover'].mean())
    # Mean wind speed
    result.append(tmp_df['windSpeed'].mean())
    result.append(tmp_df['visibility'].mean())
    result.append(tmp_df['pressure'].mean())
    result.append(tmp_df['humidity'].mean())
    result.append(tmp_df['windBearing'].mean())
    # Total precipitation
    result.append(tmp_df['precipTotal'].max())
    # Total yield
    result.append(tmp_df['Yield'].max())
    return result

## Data

In [4]:
cwd = os.getcwd()
df_2013 = pd.read_pickle(os.path.join(cwd,'data','df_2013_clean.df'))
df_2014 = pd.read_pickle(os.path.join(cwd,'data','df_2014_clean.df'))

In [5]:
df_2013['Location'] = list(zip(df_2013['Longitude'], df_2013['Latitude']))
locs_2013 = df_2013['Location'].unique().tolist()
len(locs_2013)

1014

In [6]:
df_2014['Location'] = list(zip(df_2014['Longitude'], df_2014['Latitude']))
locs_2014 = df_2014['Location'].unique().tolist()
len(locs_2014)

1035

In [7]:
# Union of locations without repetitions
elevation = {}
for loc in locs_2013:
    elevation[loc] = 0
for loc in locs_2014:
    if loc in elevation:
        pass
    else:
        elevation[loc] = 0

In [8]:
# The 'precipAccumulation' column aggregates the total precipitation per day. Now, calculate 
# the total cumulative sum. 
df_2013['precipTotal'] = df_2013.groupby(by='Location')['precipAccumulation'].apply(lambda x: x.cumsum())
df_2014['precipTotal'] = df_2014.groupby(by='Location')['precipAccumulation'].apply(lambda x: x.cumsum())

In [9]:
# Daily average temperature as average between min and max
df_2013['temperatureAverage'] = (df_2013['temperatureMax'] + df_2013['temperatureMin']) / 2.
df_2014['temperatureAverage'] = (df_2014['temperatureMax'] + df_2014['temperatureMin']) / 2.

## Features

Each location comes with:

* longitude
* latitude

The features I am going to engineer for each location are:

* the total amount of precipitation
* the minimum average temperature in a consecutive 30-day period
* the maximum average temperature in a consecutive 30-day period
* ratio of maximum average NDVI in a consecutive 30-day period and its respective minimum
* the mean temperature difference between daily min/max temperatures
* the standard deviation of the above mean
* the total average wind speed

During the engineering I will keep both years (2013 and 2014) separate. Even though these data cover mostly the same locations (~>80% overlap), weather conditions and yield is likely to be different. Keeping them separate provides additional data points.

## Exclude locations with only very few measurements across the growing period

Removing locations with very few records to perform efficient aggregation.

In [10]:
locs = df_2013['Location'].unique().tolist()
print(len(locs))
n_records_2013 = df_2013.groupby(by='Location').agg({'Location': {'Count' : lambda x: x.count()}})
n_records_2013['Location']['Count'].value_counts().sort_index(ascending=False)
klocs = n_records_2013[n_records_2013['Location']['Count'] >= 153].index.get_level_values('Location').values
locs_2013 = df_2013['Location'][df_2013['Location'].isin(klocs)].unique().tolist()
print(len(locs_2013))
#
locs = df_2014['Location'].unique().tolist()
print(len(locs))

n_records_2014 = df_2014.groupby(by='Location').agg({'Location': {'Count' : lambda x: x.count()}})
n_records_2014['Location']['Count'].value_counts().sort_index(ascending=False)
klocs = n_records_2014[n_records_2014['Location']['Count'] >= 153].index.get_level_values('Location').values
locs_2014 = df_2014['Location'][df_2014['Location'].isin(klocs)].unique().tolist()
print(len(locs_2014))

1014

C:\Users\Rashi\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py:1315: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

955
1035

C:\Users\Rashi\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py:1315: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

982

## 2013

In [11]:
df_2013.head()

,Latitude,Longitude,Date,cloudCover,dewPoint,humidity,precipIntensity,precipProbability,precipAccumulation,precipTypeIsRain,...,temperatureMin,visibility,windBearing,windSpeed,NDVI,DayInSeason,Yield,Location,precipTotal,temperatureAverage
0,46.811686,-118.695237,2013-11-30,0.00,29.53,0.91,0.0000,0.00,0.000,0,...,27.48,2.46,214,1.18,134.110657,0,35.7,"(-118.6952372, 46.81168579999999)",0.000,31.590
1,46.929839,-118.352109,2013-11-30,0.00,29.77,0.93,0.0001,0.05,0.000,1,...,26.92,2.83,166,1.01,131.506592,0,35.7,"(-118.35210929999998, 46.9298391)",0.000,31.010
2,47.006888,-118.510160,2013-11-30,0.00,29.36,0.94,0.0001,0.06,0.020,0,...,26.95,2.95,158,1.03,131.472946,0,35.7,"(-118.5101603, 47.0068881)",0.020,30.165
3,47.162342,-118.699677,2013-11-30,0.91,29.47,0.94,0.0002,0.15,0.036,0,...,27.17,2.89,153,1.84,131.288300,0,35.7,"(-118.6996774, 47.1623419)",0.036,30.180
4,47.157512,-118.434056,2013-11-30,0.91,29.86,0.94,0.0003,0.24,0.000,1,...,27.07,2.97,156,1.85,131.288300,0,35.7,"(-118.43405590000002, 47.157512)",0.000,30.460

In [12]:
features = ['longitude',
            'latitude',
            'temp_min',
            'temp_max',
            'NDVI',
            'dewPoint',
            'cloudCover',
            'mean_wind_speed',
            'visibility',
            'pressure',
            'humidity',
            'windBearing',
            'total_precipitation',
            'yield',
           ]

df_2013_new = pd.DataFrame(columns=features)

In [13]:
now = time.time()

for idx,loc in enumerate(locs_2013):
    tmp_df = df_2013[df_2013['Location'] == loc]
    (temp_min,
     temp_max,
     NDVI,
     dewPoint,
     cloudCover,
     mean_wind_speed,
     visibility,
     pressure,
     humidity,
     windBearing,
     total_precipitation,
     total_yield)=calculate_features(tmp_df)
    longitude = loc[0]
    latitude = loc[1]
    observations = {'longitude': longitude, 
        'latitude': latitude,
        'temp_min': temp_min,
        'temp_max': temp_max,
        'NDVI': NDVI,
        'dewPoint': dewPoint,
        'cloudCover': cloudCover,
        'mean_wind_speed': mean_wind_speed,  
        'visibility': visibility,
        'pressure': pressure,
        'humidity': humidity,
        'windBearing': windBearing,     
        'total_precipitation': total_precipitation,
        'yield': total_yield,
       }
    df_2013_new.loc[idx] = pd.Series(observations)

In [14]:
len(locs_2013)

955

In [15]:
df_2013_new.shape

(955, 14)

In [16]:
df_2013_new.head(10)

,longitude,latitude,temp_min,temp_max,NDVI,dewPoint,cloudCover,mean_wind_speed,visibility,pressure,humidity,windBearing,total_precipitation,yield
0,-118.695237,46.811686,22.090000,62.033000,141.646755,29.563710,0.013118,5.298548,9.110323,1019.501398,0.648065,190.510753,9.982,35.7
1,-118.352109,46.929839,21.140909,60.183833,140.507124,28.856667,0.016667,5.594247,8.958817,1019.380914,0.665430,171.150538,12.312,35.7
2,-118.510160,47.006888,20.644545,59.363000,140.382297,27.633280,0.210054,6.132742,8.939194,1019.169731,0.665591,162.500000,13.750,35.7
3,-118.699677,47.162342,20.151818,59.682000,140.460301,27.493011,0.248817,6.120430,8.904409,1019.087473,0.660914,161.365591,12.934,35.7
4,-118.434056,47.157512,20.138182,58.143167,139.764175,27.082796,0.281505,6.055968,8.758548,1018.923817,0.671452,158.682796,16.644,35.7
5,-118.958859,47.150327,21.740833,61.464167,140.844740,27.290269,0.015645,5.320806,9.123387,1019.207527,0.633602,199.134409,8.905,35.7
6,-98.330851,36.995835,28.731667,71.526500,148.690690,29.837796,0.025806,9.218011,9.264731,1017.014516,0.610591,183.268817,47.256,14.4
7,-98.404629,36.988813,28.703833,71.522333,150.153240,29.731828,0.025269,9.210806,9.268011,1017.010323,0.608871,181.661290,51.077,14.4
8,-98.319893,36.702452,29.362167,72.147500,149.131640,30.987043,0.030753,9.504355,9.253118,1017.067151,0.622957,182.451613,55.124,14.4
9,-98.539816,36.628781,29.471167,72.077000,149.728282,30.951720,0.026452,9.398011,9.284892,1017.061452,0.618011,184.172043,67.264,14.4

## 2014

In [17]:
df_2014.head()

,Latitude,Longitude,Date,cloudCover,dewPoint,humidity,precipIntensity,precipProbability,precipAccumulation,precipTypeIsRain,...,temperatureMin,visibility,windBearing,windSpeed,NDVI,DayInSeason,Yield,Location,precipTotal,temperatureAverage
0,46.929839,-118.352109,2014-11-30,0.00,6.77,0.69,0.0,0.0,0.0,0,...,6.96,10.00,9,3.80,136.179718,0,35.6,"(-118.35210929999998, 46.9298391)",0.0,15.445
1,47.150327,-118.958859,2014-11-30,0.00,6.66,0.65,0.0,0.0,0.0,0,...,8.71,10.00,352,6.03,135.697540,0,35.6,"(-118.95885919999999, 47.15032670000001)",0.0,17.295
2,46.811686,-118.695237,2014-11-30,0.00,6.55,0.67,0.0,0.0,0.0,0,...,8.26,10.00,25,3.59,135.676956,0,35.6,"(-118.6952372, 46.81168579999999)",0.0,16.465
3,47.162342,-118.699677,2014-11-30,0.03,7.32,0.69,0.0,0.0,0.0,0,...,8.10,10.00,1,5.18,135.005798,0,35.6,"(-118.6996774, 47.1623419)",0.0,16.790
4,47.157512,-118.434056,2014-11-30,0.04,7.62,0.70,0.0,0.0,0.0,0,...,8.32,9.99,5,4.69,134.803864,0,35.6,"(-118.43405590000002, 47.157512)",0.0,16.575

In [18]:
features = ['longitude',
            'latitude',
            'temp_min',
            'temp_max',
            'NDVI',
            'dewPoint',
            'cloudCover',
            'mean_wind_speed',
            'visibility',
            'pressure',
            'humidity',
            'windBearing',
            'total_precipitation',
            'yield',
           ]

df_2014_new = pd.DataFrame(columns=features)

In [19]:
now = time.time()

for idx,loc in enumerate(locs_2014):
    tmp_df = df_2014[df_2014['Location'] == loc]
    (temp_min,
     temp_max,
     NDVI,
     dewPoint,
     cloudCover,
     mean_wind_speed,
     visibility,
     pressure,
     humidity,
     windBearing,
     total_precipitation,
     total_yield)=calculate_features(tmp_df)
    longitude = loc[0]
    latitude = loc[1]
    observations = {'longitude': longitude, 
        'latitude': latitude,
        'temp_min': temp_min,
        'temp_max': temp_max,
        'NDVI': NDVI,
        'dewPoint': dewPoint,
        'cloudCover': cloudCover,
        'mean_wind_speed': mean_wind_speed,  
        'visibility': visibility,
        'pressure': pressure,
        'humidity': humidity,
        'windBearing': windBearing,     
        'total_precipitation': total_precipitation,
        'yield': total_yield,
       }
    df_2014_new.loc[idx] = pd.Series(observations)

Exec. time: 24.25 s

In [20]:
len(locs_2014)

982

In [21]:
df_2014_new.shape

(982, 14)

In [22]:
df_2014_new.head(10)

,longitude,latitude,temp_min,temp_max,NDVI,dewPoint,cloudCover,mean_wind_speed,visibility,pressure,humidity,windBearing,total_precipitation,yield
0,-118.352109,46.929839,29.588000,62.185833,141.370162,33.234086,0.072849,4.202903,8.987419,1019.317849,0.687581,161.564516,3.362,35.6
1,-118.958859,47.150327,29.681000,63.494667,141.585205,32.690430,0.066452,4.044194,9.179892,1019.305484,0.675161,194.586022,1.536,35.6
2,-118.695237,46.811686,30.269500,63.789667,142.598213,33.942957,0.061398,3.991398,8.997151,1019.282742,0.673387,182.591398,2.472,35.6
3,-118.699677,47.162342,29.487500,62.002333,140.987673,32.532742,0.227043,4.630054,9.025860,1019.294086,0.694409,149.215054,3.528,35.6
4,-118.434056,47.157512,28.834833,60.857667,140.873097,31.797151,0.260269,4.717097,8.869355,1019.246022,0.696237,145.704301,4.317,35.6
5,-118.510160,47.006888,29.496000,61.706000,141.061506,32.539516,0.231398,4.679677,9.010591,1019.286613,0.697849,148.709677,3.671,35.6
6,-98.454318,36.508221,31.529167,65.112000,149.659359,37.675269,0.100645,8.180699,9.004677,1019.181828,0.711774,158.129032,10.565,29.3
7,-98.444745,36.650698,31.417333,65.034000,149.100936,37.342796,0.100806,8.170323,9.005054,1019.183226,0.707581,159.629032,13.368,29.3
8,-98.319893,36.702452,31.339000,65.082167,149.621839,36.919785,0.106237,8.287366,8.988978,1019.183333,0.698602,158.903226,12.767,29.3
9,-98.539816,36.628781,31.370833,65.004333,149.489254,37.262688,0.100269,8.169570,9.008172,1019.183656,0.707043,158.403226,14.993,29.3

In [23]:
df_2013_new.columns

Index(['longitude', 'latitude', 'temp_min', 'temp_max', 'NDVI', 'dewPoint',
       'cloudCover', 'mean_wind_speed', 'visibility', 'pressure', 'humidity',
       'windBearing', 'total_precipitation', 'yield'],
      dtype='object')

In [24]:
df_2014_new.columns

Index(['longitude', 'latitude', 'temp_min', 'temp_max', 'NDVI', 'dewPoint',
       'cloudCover', 'mean_wind_speed', 'visibility', 'pressure', 'humidity',
       'windBearing', 'total_precipitation', 'yield'],
      dtype='object')

## Save features to disk

In [25]:
df_2013_new.to_pickle(os.path.join('data','df_2013_features.df'))
df_2014_new.to_pickle(os.path.join('data','df_2014_features.df'))